---

- hosts: centos.my
  become: yes
  tasks:
  -  name: Install postgresql repo
     yum:
        name=https://download.postgresql.org/pub/repos/yum/reporpms/EL-7-x86_64/pgdg-redhat-repo-latest.noarch.rpm
        state=present

  -  name: Install postgresql12-server on RedHat Family
     yum:
        name=postgresql12-server
        state=present
