---

- hosts: ubuntu.my
  become: yes
  tasks:
  -  name: Install zabbix-agent on Ubuntu
     apt:
        name=zabbix-agent
        state=latest
     when:
        ansible_os_family == "Debian"
     notify:
        zabbix-agent systemd
  - name: replace line
    lineinfile: 
      path: /etc/zabbix/zabbix_agentd.conf 
      regexp: '^Server=' 
      line: 'Server=158.160.172.9'
      backrefs: yes
  handlers:
  - name: zabbix-agent systemd
    systemd:
     name: zabbix-agent.service
     enabled: yes
     state: started
